name: Dayly
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.6.9
  collection: ^1.14.13
  community_material_icon: ^5.3.45
  cupertino_icons: ^0.1.3
  dartz: ^0.9.2
  device_calendar: ^3.1.0
  flutter_bloc: ^6.1.1
  flutter_circular_slider: ^2.5.0
  flutter_keyboard_visibility: ^4.0.2
  flutter_local_notifications: ^3.0.2
  flutter_slidable: ^0.5.7
  flutter_staggered_grid_view: ^0.3.2
  flutter_statusbarcolor: ^0.2.3
  flutter_sticky_header: ^0.5.0
  flutter_xlider: ^3.4.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  injectable: ^1.0.5
  intl: ^0.16.1
  moor: ^3.4.0
  reorderables: ^0.3.2
  rxdart: ^0.25.0
  scroll_to_index: ^1.0.6
  scrollable_positioned_list: ^0.1.8
  shared_preferences: ^0.5.8
  sliding_up_panel: ^1.0.2
  smart_select: ^4.3.2
  smooth_page_indicator: ^0.2.0
  sqlite3_flutter_libs: ^0.2.0
  stop_watch_timer: ^0.7.0
  swipedetector: ^1.2.0
  theme_provider: ^0.4.0+1
  timer_builder: ^1.3.0
  tuple: ^1.0.3
  url_launcher: ^5.7.10
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^0.40.6
  auto_route_generator: ^0.6.9
  build_runner: null
  flutter_launcher_icons: ^0.8.0
  freezed: ^0.12.2
  google_fonts: ^1.1.0
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.1
  lint: ^1.3.0
  moor_generator: ^3.4.0
  rename: ^1.2.0
  test: null

flutter_icons:
  ios: true
  android: true
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  image_path_ios: "assets/icon/app_icon.png"
  image_path_android: "assets/icon/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
